'''n = int(input())

for x in range(n):
  if x < n/2:
    print('*'*(2*x+1)+(2*(n-2*x)-2)*' '+'*'*(2*x+1))
  elif x > n/2:
    print('*'*(2*(n-x-1)+1)+(2*(n-2*(n-x-1))-2)*' '+'*'*(2*(n-x-1)+1))
  else:
    print('*'*2*n)
'''
n = int(input())

if n == 0:
  print(" * * * ")
  print("*     *")
  print("*     *")
  print("*     *")
  print("       ")
  print("*     *")
  print("*     *")
  print("*     *")
  print(" * * * ")
elif n == 1:
  print("      *")
  print("      *")
  print("      *")
  print("       ")
  print("      *")
  print("      *")
  print("      *")
  print("")
elif n == 2:
  print(" * * * ")
  print("      *")
  print("      *")
  print("      *")
  print(" * * * ")
  print("*      ")
  print("*      ")
  print("*      ")
  print(" * * * ")
elif n == 3:
  print(" * * * ")
  print("      *")
  print("      *")
  print("      *")
  print(" * * * ")
  print("      *")
  print("      *")
  print("      *")
  print(" * * * ")
elif n == 4:
  print("       ")
  print("*     *")
  print("*     *")
  print("*     *")
  print(" * * * ")
  print("      *")
  print("      *")
  print("      *")
  print("       ")
elif n == 5:
  print(" * * * ")
  print("*      ")
  print("*      ")
  print("*      ")
  print(" * * * ")
  print("      *")
  print("      *")
  print("      *")
  print(" * * * ")
elif n == 6:
  print(" * * * ")
  print("*      ")
  print("*      ")
  print("*      ")
  print(" * * * ")
  print("*     *")
  print("*     *")
  print("*     *")
  print(" * * * ")
elif n == 7:
  print(" * * * ")
  print("      *")
  print("      *")
  print("      *")
  print("       ")
  print("      *")
  print("      *")
  print("      *")
  print("       ")
elif n == 8:
  print(" * * * ")
  print("*     *")
  print("*     *")
  print("*     *")
  print(" * * * ")
  print("*     *")
  print("*     *")
  print("*     *")
  print(" * * * ")
elif n == 9:
  print(" * * * ")
  print("*     *")
  print("*     *")
  print("*     *")
  print(" * * * ")
  print("      *")
  print("      *")
  print("      *")
  print(" * * * ")
print('\n')